Sfml render window
B05-232/plug-standard pull request #21
Opened 2023-11-21 20:02 UTC by DenzeL2004

2023-11-21 21:31 UTC, MeerkatBoss requested changes

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderTarget.h
> +void coppyToSFMLTexture      (sf::Texture &sf_texture, const plug::Texture &plug_texture);
`copy`, not `coppy`

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderWindow/RenderWindow.cpp
> +#include "Impl/Graphics/RenderTarget/RenderTarget.h"
No such file. Maybe you meant "Plug/Graphics.h"?

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderWindow/RenderWindow.h
> +        unsigned getNativeHandle(void) const;
This must be `virtual` and `override`

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderWindow/RenderWindow.h
> +        plug::Vec2d getMouseCoord(void) const;
Is this necessary?

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderTarget.cpp
What even is this file? Looks like just a set of random helper functions that should not have been here

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderTarget.h
Same as RenderTarget.cpp

2023-11-21 21:31 UTC, MeerkatBoss commented on src/Impl/RenderTarget/RenderWindow/RenderWindow.h
> +class RenderWindow : public plug::RenderTarget
I think this should be named something like `SfmlRenderTarget` to avoid confusion with SDL2 implementation

2023-11-22 14:12 UTC, Sigmarik requested changes
`SfmlRenderTarget::getNativeHandle` was not implemented propperly

2023-11-22 14:12 UTC, Sigmarik commented on src/Impl/RenderTarget/SfmlRenderTarget/RenderTarget.cpp
> +unsigned SfmlRenderTarget::getNativeHandle(void) const { return 0; }
This is not how it is supposed to work...

Plus, there is an issue with this format. I recommend you check it out.
https://github.com/B05-232/plug-standard/issues/30

2023-11-22 15:25 UTC, MeerkatBoss approved these changes

2023-11-22 15:28 UTC, Sigmarik approved these changes

2023-11-22 15:28 UTC, merged